/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/editProfile`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/recipeDetail`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/recipe` | `/recipe`; params?: Router.UnknownInputParams; } | { pathname: `/context/UserContext`; params?: Router.UnknownInputParams; } | { pathname: `/lib/auth`; params?: Router.UnknownInputParams; } | { pathname: `/lib/supabase`; params?: Router.UnknownInputParams; } | { pathname: `/models/Meals`; params?: Router.UnknownInputParams; } | { pathname: `/models/User`; params?: Router.UnknownInputParams; } | { pathname: `/services/authApi`; params?: Router.UnknownInputParams; } | { pathname: `/services/recipeApi`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/editProfile`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/recipeDetail`; params?: Router.UnknownOutputParams; } | { pathname: `/register`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/recipe` | `/recipe`; params?: Router.UnknownOutputParams; } | { pathname: `/context/UserContext`; params?: Router.UnknownOutputParams; } | { pathname: `/lib/auth`; params?: Router.UnknownOutputParams; } | { pathname: `/lib/supabase`; params?: Router.UnknownOutputParams; } | { pathname: `/models/Meals`; params?: Router.UnknownOutputParams; } | { pathname: `/models/User`; params?: Router.UnknownOutputParams; } | { pathname: `/services/authApi`; params?: Router.UnknownOutputParams; } | { pathname: `/services/recipeApi`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/editProfile${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/recipeDetail${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/recipe${`?${string}` | `#${string}` | ''}` | `/recipe${`?${string}` | `#${string}` | ''}` | `/context/UserContext${`?${string}` | `#${string}` | ''}` | `/lib/auth${`?${string}` | `#${string}` | ''}` | `/lib/supabase${`?${string}` | `#${string}` | ''}` | `/models/Meals${`?${string}` | `#${string}` | ''}` | `/models/User${`?${string}` | `#${string}` | ''}` | `/services/authApi${`?${string}` | `#${string}` | ''}` | `/services/recipeApi${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/editProfile`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/recipeDetail`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/recipe` | `/recipe`; params?: Router.UnknownInputParams; } | { pathname: `/context/UserContext`; params?: Router.UnknownInputParams; } | { pathname: `/lib/auth`; params?: Router.UnknownInputParams; } | { pathname: `/lib/supabase`; params?: Router.UnknownInputParams; } | { pathname: `/models/Meals`; params?: Router.UnknownInputParams; } | { pathname: `/models/User`; params?: Router.UnknownInputParams; } | { pathname: `/services/authApi`; params?: Router.UnknownInputParams; } | { pathname: `/services/recipeApi`; params?: Router.UnknownInputParams; };
    }
  }
}
